<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PRO-RAET-AVINASH" failures="1" tests="5" name="RetryMultipleFailedTest" time="0.041" errors="0" timestamp="05 Oct 2018 06:44:17 GMT">
  <testcase classname="myTest.RetryAtRunTime" name="Test1" time="0.009">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="myTest.RetryAtRunTime" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="myTest.RetryAtRunTime" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="myTest.RetryAtRunTime" name="Test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at myTest.RetryAtRunTime.Test1(RetryAtRunTime.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="myTest.RetryAtRunTime" name="Test2" time="0.001"/>
</testsuite> <!-- RetryMultipleFailedTest -->
